# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore JpegXmpWritePluginMDE.sln
    - name: Build
      run: dotnet build JpegXmpWritePluginMDE.sln --configuration Release
    - name: Test net8.0
      run: dotnet test --verbosity normal --configuration Release --no-build -f net8.0 JpegXmpWritePluginMDE.Tests\JpegXmpWritePluginMDE.Tests.csproj
